"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .models_attachment import ModelsAttachment
from .models_from import ModelsFrom
from .models_replyto import ModelsReplyTo
from .models_to import ModelsTo
from typing import List, Optional


@dataclasses.dataclass
class Groups:
    pass


@dataclasses.dataclass
class Headers:
    pass


@dataclasses.dataclass
class ModelsEmailMessage:
    amp_body: Optional[str] = dataclasses.field(default=None)
    attachments: Optional[List[ModelsAttachment]] = dataclasses.field(default=None)
    from_: Optional[ModelsFrom] = dataclasses.field(default=None)
    groups: Optional[Groups] = dataclasses.field(default=None)
    headers: Optional[Headers] = dataclasses.field(default=None)
    html_body: Optional[str] = dataclasses.field(default=None)
    ippool: Optional[str] = dataclasses.field(default=None)
    pre_text: Optional[str] = dataclasses.field(default=None)
    reply_to: Optional[ModelsReplyTo] = dataclasses.field(default=None)
    subject: Optional[str] = dataclasses.field(default=None)
    template: Optional[str] = dataclasses.field(default=None)
    text_body: Optional[str] = dataclasses.field(default=None)
    to: Optional[List[ModelsTo]] = dataclasses.field(default=None)
    track_clicks: Optional[bool] = dataclasses.field(default=None)
    track_opens: Optional[bool] = dataclasses.field(default=None)
    

