"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import models_attachment as shared_models_attachment
from ..shared import models_from as shared_models_from
from ..shared import models_replyto as shared_models_replyto
from ..shared import models_to as shared_models_to
from typing import Optional



@dataclasses.dataclass
class ModelsEmailMessageGroups:
    pass



@dataclasses.dataclass
class ModelsEmailMessageHeaders:
    pass



@dataclasses.dataclass
class ModelsEmailMessage:
    amp_body: Optional[str] = dataclasses.field(default=None)
    attachments: Optional[list[shared_models_attachment.ModelsAttachment]] = dataclasses.field(default=None)
    from_: Optional[shared_models_from.ModelsFrom] = dataclasses.field(default=None)
    groups: Optional[ModelsEmailMessageGroups] = dataclasses.field(default=None)
    headers: Optional[ModelsEmailMessageHeaders] = dataclasses.field(default=None)
    html_body: Optional[str] = dataclasses.field(default=None)
    ippool: Optional[str] = dataclasses.field(default=None)
    pre_text: Optional[str] = dataclasses.field(default=None)
    reply_to: Optional[shared_models_replyto.ModelsReplyTo] = dataclasses.field(default=None)
    subject: Optional[str] = dataclasses.field(default=None)
    template: Optional[str] = dataclasses.field(default=None)
    text_body: Optional[str] = dataclasses.field(default=None)
    to: Optional[list[shared_models_to.ModelsTo]] = dataclasses.field(default=None)
    track_clicks: Optional[bool] = dataclasses.field(default=None)
    track_opens: Optional[bool] = dataclasses.field(default=None)
    

