"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from typing import Optional


@dataclasses.dataclass
class ModelsCopyToCustomFields:
    pass


@dataclasses.dataclass
class ModelsCopyTo:
    custom_fields: Optional[ModelsCopyToCustomFields] = dataclasses.field(default=None)
    email: Optional[str] = dataclasses.field(default=None)
    name: Optional[str] = dataclasses.field(default=None)
    

