"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import models_emailerrorcode as shared_models_emailerrorcode
from typing import Optional



@dataclasses.dataclass
class ModelsEmailResponse:
    error_code: Optional[shared_models_emailerrorcode.ModelsEmailErrorCode] = dataclasses.field(default=None)
    message: Optional[str] = dataclasses.field(default=None)
    message_id: Optional[str] = dataclasses.field(default=None)
    submitted_at: Optional[int] = dataclasses.field(default=None)
    to: Optional[str] = dataclasses.field(default=None)
    

